rd Debug /S /Q
rd Debug64 /S /Q
rd x64 /S /Q
rd ipch /S /Q

rd QuantBox.XAPI\bin /S /Q
rd QuantBox.XAPI\obj /S /Q

rd QuantBox_CTP_Quote\Debug /S /Q
rd QuantBox_CTP_Trade\Debug /S /Q
rd QuantBox_DFITC_Level2\Debug /S /Q
rd QuantBox_Esunny_HistoricalData\Debug /S /Q
rd QuantBox_Femas_Quote\Debug /S /Q
rd QuantBox_Femas_Trade\Debug /S /Q
rd QuantBox_Kingstar_Quote\Debug /S /Q
rd QuantBox_Kingstar_Trade\Debug /S /Q
rd QuantBox_KingstarStock_Trade\Debug /S /Q
rd QuantBox_LTS_Level2\Debug /S /Q
rd QuantBox_LTS_Quote\Debug /S /Q
rd QuantBox_LTS_Trade\Debug /S /Q
rd QuantBox_Queue\Debug /S /Q
rd QuantBox_Kingstar_Quote\Debug /S /Q
rd QuantBox_Kingstar_Trade\Debug /S /Q
rd QuantBox_KingstarGold\Debug /S /Q
rd QuantBox_XSpeed_Quote\Debug /S /Q
rd QuantBox_XSpeed_Trade\Debug /S /Q
rd QuantBox_XSpeedStock_Quote\Debug /S /Q
rd QuantBox_XSpeedStock_Trade\Debug /S /Q
rd QuantBox_ZeroMQ_Quote\Debug /S /Q
rd QuantBox_TongShi_Quote\Debug /S /Q

rd QuantBox_CTP_Quote\Debug64 /S /Q
rd QuantBox_CTP_Trade\Debug64 /S /Q
rd QuantBox_DFITC_Level2\Debug64 /S /Q
rd QuantBox_Esunny_HistoricalData\Debug64 /S /Q
rd QuantBox_Femas_Quote\Debug64 /S /Q
rd QuantBox_Femas_Trade\Debug64 /S /Q
rd QuantBox_Kingstar_Quote\Debug64 /S /Q
rd QuantBox_Kingstar_Trade\Debug64 /S /Q
rd QuantBox_KingstarStock_Trade\Debug64 /S /Q
rd QuantBox_LTS_Level2\Debug64 /S /Q
rd QuantBox_LTS_Quote\Debug64 /S /Q
rd QuantBox_LTS_Trade\Debug64 /S /Q
rd QuantBox_Queue\Debug64 /S /Q
rd QuantBox_Kingstar_Quote\Debug64 /S /Q
rd QuantBox_Kingstar_Trade\Debug64 /S /Q
rd QuantBox_KingstarGold\Debug64 /S /Q
rd QuantBox_XSpeed_Quote\Debug64 /S /Q
rd QuantBox_XSpeed_Trade\Debug64 /S /Q
rd QuantBox_XSpeedStock_Quote\Debug64 /S /Q
rd QuantBox_XSpeedStock_Trade\Debug64 /S /Q

rd QuantBox_CTP_Quote\Release /S /Q
rd QuantBox_CTP_Trade\Release /S /Q
rd QuantBox_DFITC_Level2\Release /S /Q
rd QuantBox_Esunny_HistoricalData\Release /S /Q
rd QuantBox_Femas_Quote\Release /S /Q
rd QuantBox_Femas_Trade\Release /S /Q
rd QuantBox_Kingstar_Quote\Release /S /Q
rd QuantBox_Kingstar_Trade\Release /S /Q
rd QuantBox_KingstarStock_Trade\Release /S /Q
rd QuantBox_LTS_Level2\Release /S /Q
rd QuantBox_LTS_Quote\Release /S /Q
rd QuantBox_LTS_Trade\Release /S /Q
rd QuantBox_Queue\Release /S /Q
rd QuantBox_Kingstar_Quote\Release /S /Q
rd QuantBox_Kingstar_Trade\Release /S /Q
rd QuantBox_KingstarGold\Release /S /Q
rd QuantBox_XSpeed_Quote\Release /S /Q
rd QuantBox_XSpeed_Trade\Release /S /Q
rd QuantBox_XSpeedStock_Quote\Release /S /Q
rd QuantBox_XSpeedStock_Trade\Release /S /Q

rd QuantBox_CTP_Quote\x64 /S /Q
rd QuantBox_CTP_Trade\x64 /S /Q
rd QuantBox_DFITC_Level2\x64 /S /Q
rd QuantBox_Esunny_HistoricalData\x64 /S /Q
rd QuantBox_Femas_Quote\x64 /S /Q
rd QuantBox_Femas_Trade\x64 /S /Q
rd QuantBox_Kingstar_Quote\x64 /S /Q
rd QuantBox_Kingstar_Trade\x64 /S /Q
rd QuantBox_KingstarStock_Trade\x64 /S /Q
rd QuantBox_LTS_Level2\x64 /S /Q
rd QuantBox_LTS_Quote\x64 /S /Q
rd QuantBox_LTS_Trade\x64 /S /Q
rd QuantBox_Queue\x64 /S /Q
rd QuantBox_Kingstar_Quote\x64 /S /Q
rd QuantBox_Kingstar_Trade\x64 /S /Q
rd QuantBox_KingstarGold\x64 /S /Q
rd QuantBox_XSpeed_Quote\x64 /S /Q
rd QuantBox_XSpeed_Trade\x64 /S /Q
rd QuantBox_XSpeedStock_Quote\x64 /S /Q
rd QuantBox_XSpeedStock_Trade\x64 /S /Q
